apiVersion: v1
kind: Service
metadata:
  name: task-app-service
spec:
  selector:
    app: taskdevops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  
