name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd REST_API  # Change to the directory containing your FastAPI code
        DOCKER_TAG=${{ github.event.release.tag_name }}
        docker build -t sajedul5/task_devops:${DOCKER_TAG} .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push sajedul5/task_devops:${DOCKER_TAG}
