name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # DOCKER_TAG: v1
      run: |
        cd REST_API  
        # DOCKER_TAG=${{ github.event.release.tag_name }}
        # if [ -z "$DOCKER_TAG" ]; then
        #   echo "ERROR: Release tag is empty."
        #   exit 1
        # fi
        docker build -t sajedul5/task_devops:v1 .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push sajedul5/task_devops:v1
